name: 'Generate'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: |
          ls
      - name: pwd
        run: |
          pwd
      - name: generate
        run: bash generate_index.md
      - name: git setting
        run: |
          git config --local user.email "kgwryk28@gmail.com"
          git config --local user.name "warawara28"
      - name: Commit files
        run: |
          git add .
          git commit -m "Generate index file automatically" -a
          git pull
          git push origin master
